// WARNING: DO NOT EDIT THIS FILE, IT IS AUTOGENERATED
module.exports = {
  addonType: "plugin",
  id: "piranha305_timesystem",
  name: "Time System",
  version: "1.0.0.0",
  category:
    // "3d",
    // "data-and-storage",
    // "form-controls",
    // "input",
    // "media",
    // "monetisation",
    // "platform-specific",
    // "web",
    // "other"
    "general",
  author: "piranha305",
  website: "https://www.construct.net",
  documentation: "https://www.construct.net",
  description: "Description",
  // addonUrl: "https://www.construct.net/en/make-games/addons/####/XXXX", // displayed in auto-generated docs
  // githubUrl: "https://github.com/skymen/XXXX", // displays latest release version in auto-generated docs
  // icon: "icon.svg", // defaults to "icon.svg" if omitted
  type: "object",   // world, object, dom
  domSideScripts: [
    // "domSide.js", // no need to include "c3runtime/" prefix
  ],
  fileDependencies: [
    /*
    {
      filename: "filename.js", // no need to include "c3runtime/" prefix
      type:
        "copy-to-output"
        "inline-script"
        "external-dom-script"
        "external-runtime-script"
        "external-css"

      // for copy-to-output only
      // fileType: "image/png"
    }
    */
  ],
  info: {
    // world only
    defaultImageUrl: null,
    Set: {
      // world only
      IsResizable: false,
      IsRotatable: false,
      Is3D: false,
      HasImage: false,
      IsTiled: false,
      SupportsZElevation: false,
      SupportsColor: false,
      SupportsEffects: false,
      MustPreDraw: false,

      // object only
      IsSingleGlobal: true,

      // world and object
      CanBeBundled: true,
      IsDeprecated: false,
      GooglePlayServicesEnabled: false,
    },
    AddCommonACEs: {
      // world only
      Position: false,
      SceneGraph: false,
      Size: false,
      Angle: false,
      Appearance: false,
      ZOrder: false,
    },
  },
  properties: [
    {
      type: "check",
      id: "Enabled",
      name: "Enabled",
      desc: "Enable or disable the timne system behavior. (if disabled will not tick)",
      options: {
        initialValue: true,
      },
    },
    {
      type: "float",
      id: "TickRate",
      name: "Tick Rate",
      desc: "How many seconds between each tick. (default 1)",
      options: {
        initialValue: 1,
        minValue: 0,
      },
    },
    {
      type: "float",
      id: "TicksPerMintue",
      name: "Ticks Per Mintue",
      desc: "How many ticks per mintue. (default 60)",
      options: {
        initialValue: 60,
        minValue: 0,
      },
    },
    {
      type: "integer",
      id: "CurrentMinute",
      name: "Current Minute",
      desc: "The current minute.",
      options: {
        initialValue: 0,
        minValue: 0,
        maxValue: 59,
      },
    },
    {
      type: "integer",
      id: "CurrentHour",
      name: "Current Hour",
      desc: "The current hour.",
      options: {
        initialValue: 0,
        minValue: 0,
        maxValue: 23,
      },
    },
    {
      type: "integer",
      id: "CurrentDay",
      name: "Current Day",
      desc: "The current day.",
      options: {
        initialValue: 1,
        minValue: 1,
        maxValue: 31,
      },
    },
    {
      type: "integer",
      id: "CurrentMonth",
      name: "Current Month",
      desc: "The current month.",
      options: {
        initialValue: 1,
        minValue: 1,
        maxValue: 12,
      },
    },
    {
      type: "integer",
      id: "CurrentYear",
      name: "Current Year",
      desc: "The current year.",
      options: {
        initialValue: 2021,
        minValue: 0,
        maxValue: 9999,
      },
    },
    {
      type: "combo",
      id: "CurrentDayOfWeek",
      name: "Current Day Of Week",
      desc: "The current day of the week.",
      options: {
        initialValue: 'sun',
        items: [
          { sun: "Sunday" },
          { mon: "Monday" },
          { tue: "Tuesday" },
          { wed: "Wednesday" },
          { thurs: "Thursday" },
          { fri: "Friday" },
          { sat: "Saturday" },
        ],
      },
    },
    {
        type: "combo",
        id: "DayPhases",
        name: "Day Phases",
        desc: "How many phases of the day. (default 4)",
        options: {
          initialValue: "four",
          items: [
            { "two": "2 Phases"},
            { "four": "4 Phases" },
            { "six": "6 Phases" },
            { "eight": "8 Phases" }
          ],
        }
    }

    // 4 phases
    // 6am - 12pm = morning
    // 12pm - 6pm = afternoon
    // 6pm - 12am = night
    // 12am - 6am = late night

    // 6 phases
    // 5am - 8am = dawn
    // 8am - 1pm = morning
    // 1pmpm - 5pm = afternoon
    // 5pm - 8pm = dusk
    // 8pm - 12am = night
    // 12am - 5am = late night

    // 8 phases
    // 5am - 8am = dawn
    // 8am - 11am = morning
    // 11am - 2pm = noon
    // 2pm - 5pm = afternoon
    // 5pm - 8pm = dusk
    // 8pm - 11pm = night
    // 11pm - 2am = midnight
    // 2am - 5am = late night
  
    
    /*
    {
      type:
        "integer"
        "float"
        "percent"
        "text"
        "longtext"
        "check"
        "font"
        "combo"
        "color"
        "object"
        "group"
        "link"
        "info"

      id: "property_id",
      options: {
        initialValue: 0,
        interpolatable: false,

        // minValue: 0, // omit to disable
        // maxValue: 100, // omit to disable

        // for type combo only
        // items: [
        //   {itemId1: "item name1" },
        //   {itemId2: "item name2" },
        // ],

        // dragSpeedMultiplier: 1, // omit to disable

        // for type object only
        // allowedPluginIds: ["Sprite", "<world>"],

        // for type link only
        // linkCallback: `function(instOrObj) {}`,
        // linkText: "Link Text",
        // callbackType:
        //   "for-each-instance"
        //   "once-for-type"

        // for type info only
        // infoCallback: `function(inst) {}`,
      },
      name: "Property Name",
      desc: "Property Description",
    }
    */
  ],
  aceCategories: {
    // follows the format id: langName
    // in the ACEs refer to categories using the id, not the name
    general: "General",
  },
  Acts: {
    /*
    SampleAction: {
      // The category of the action as it appears in the add action dialog
      category: "general",

      // Forward to the instance function name
      forward: "_SampleAction",
      // Or specify a handler function
      handler: `function () {
        // Your code here
      }`,

      // Set to true to automatically generate a script interface for this action
      // Cases where you might not want this are:
      // 1- If the action params are incompatible with the script interface
      // 2- If you don't want it to appear in the script interface
      // 3- If the script interface has a better way to achieve the same thing
      autoScriptInterface: true,

      // Set to true to highlight the action in the add action dialog
      highlight: true,

      // Set to true to hide the action in the interface. False by default if not specified.
      deprecated: false,

      // Marks the action as async. Defaults to false if not specified.
      isAsync: false,

      // list of parameters
      params: [
        {
          // The id of the parameter. This is used to generate the script interface.
          // It must be unique for each parameter.
          id: "param1",
          // The name of the parameter.
          name: "Param 1",
          // The description of the parameter.
          desc: "The first parameter",

          // The type of the parameter.
          type:
            // The following types can take a default value AND be automatically generated in the script interface
            - "string"
            - "number"
            - "any"
            - "boolean"

            // The following types can take a default value but CANNOT be automatically generated in the script interface
            - "combo"

            // The following types CANNOT take a default value AND CANNOT be automatically generated in the script interface
            - "cmp"
            - "object"
            - "objectname"
            - "layer"
            - "layout"
            - "keyb"
            - "instancevar"
            - "instancevarbool"
            - "eventvar"
            - "eventvarbool"
            - "animation"
            - "objinstancevar"

          // The default value of the parameter. Can be omitted if the type is not a string, number, any, boolean or combo.
          value: "the default value of the parameter",

          // Only for type "combo"
          items: [
            {"itemId1": "itemName1"},
            {"itemId2": "itemName2"},
            {"itemId3": "itemName3"},
          ],

          // Only for type "object"
          allowedPluginIds: ["Sprite", "TiledBg"],
        },
      ],

      // The name of the action as it appears in the add action dialog
      listName: "Sample Action",

      // The text that appears in the event sheet. Note, every single param must be used in the display text.
      // You can also use [b] and [i] tags.
      displayText: "Sample action [i]{0}[/i]",

      // The description of the action as it appears in the add action dialog
      description: "This is a sample action",
    },
    */
  },
  Cnds: {
    OnTick: {
      category : "general",
      handler: `() => { return true; }`,
      highlight : false,
      deprecated : false,
      isTrigger : true,
      params: [],
      listName : "On Tick",
      displayText : "On Tick",
      description : "Triggered every tick.",
    },
    OnMinute: {
      category : "general",
      handler: `() => { return true; }`,
      highlight : false,
      deprecated : false,
      isTrigger : true,
      params: [],
      listName : "On Minute",
      displayText : "On Minute",
      description : "Triggered every minute.",
    },
    OnHour: {
      category : "general",
      handler: `() => { return true; }`,
      highlight : false,
      deprecated : false,
      isTrigger : true,
      params: [],
      listName : "On Hour",
      displayText : "On Hour",
      description : "Triggered every hour.",
    },
    OnDay: {
      category : "general",
      handler: `() => { return true; }`,
      highlight : false,
      deprecated : false,
      isTrigger : true,
      params: [],
      listName : "On Day",
      displayText : "On Day",
      description : "Triggered every day.",
    },
    OnWeek: {
      category : "general",
      handler: `() => { return true; }`,
      highlight : false,
      deprecated : false,
      isTrigger : true,
      params: [],
      listName : "On Week",
      displayText : "On Week",
      description : "Triggered every week.",
    },
    OnMonth: {
      category : "general",
      handler: `() => { return true; }`,
      highlight : false,
      deprecated : false,
      isTrigger : true,
      params: [],
      listName : "On Month",
      displayText : "On Month",
      description : "Triggered every month.",
    },
    OnYear: {
      category : "general",
      handler: `() => { return true; }`,
      highlight : false,
      deprecated : false,
      isTrigger : true,
      params: [],
      listName : "On Year",
      displayText : "On Year",
      description : "Triggered every year.",
    },
    OnDayPhaseChange: {
      category : "general",
      handler: `() => { return true; }`,
      highlight : false,
      deprecated : false,
      isTrigger : true,
      params: [],
      listName : "On Day Phase Change",
      displayText : "On Day Phase Change",
      description : "Triggered when the day phase changes.",
    },
    /*
    SampleCondition: {
      // The category of the action as it appears in the add condition dialog
      category: "general",

      // Forward to the instance function name
      forward: "_SampleAction",
      // Or specify a handler function
      handler: `function () {
        // Your code here
      }`,

      // Set to true to automatically generate a script interface for this condition
      // Cases where you might not want this are:
      // 1- If the condition params are incompatible with the script interface
      // 2- If you don't want it to appear in the script interface
      // 3- If the script interface has a better way to achieve the same thing
      autoScriptInterface: true,

      // Set to true to highlight the condition in the add condition dialog
      highlight: true,

      // Set to true to hide the condition in the interface. False by default if not specified.
      deprecated: false,

      // special conditions properties. These can all be omitted, and they will default to the following values:
      isTrigger: false,
      isFakeTrigger: false,
      isStatic: false,
      isLooping: false,
      isInvertible: true,
      isCompatibleWithTriggers: true,

      // list of parameters
      params: [
        {
          // The id of the parameter. This is used to generate the script interface.
          // It must be unique for each parameter.
          id: "param1",
          // The name of the parameter.
          name: "Param 1",
          // The description of the parameter.
          desc: "The first parameter",

          // The type of the parameter.
          type:
            // The following types can take a default value AND be automatically generated in the script interface
            - "string"
            - "number"
            - "any"
            - "boolean"

            // The following types can take a default value but CANNOT be automatically generated in the script interface
            - "combo"

            // The following types CANNOT take a default value AND CANNOT be automatically generated in the script interface
            - "cmp"
            - "object"
            - "objectname"
            - "layer"
            - "layout"
            - "keyb"
            - "instancevar"
            - "instancevarbool"
            - "eventvar"
            - "eventvarbool"
            - "animation"
            - "objinstancevar"

          // The default value of the parameter. Can be omitted if the type is not a string, number, any, boolean or combo.
          value: "the default value of the parameter",

          // Only for type "combo"
          items: [
            {"itemId1": "itemName1"},
            {"itemId2": "itemName2"},
            {"itemId3": "itemName3"},
          ],

          // Only for type "object"
          allowedPluginIds: ["Sprite", "TiledBg"],
        },
      ],

      // The name of the condition as it appears in the add condition dialog
      listName: "Sample Condition",

      // The text that appears in the event sheet. Note, every single param must be used in the display text.
      // You can also use [b] and [i] tags.
      displayText: "Sample condition [i]{0}[/i]",

      // The description of the condition as it appears in the add condition dialog
      description: "This is a sample condition",
    },
    */
  },
  Exps: {
    CurrentTick: {
      category : "general",
      handler: `function () { return this.currentTick; }`,
      highlight : false,
      deprecated : false,
      params: [],
      returnType: "number",
      isVariadicParameters: false,
      description : "The current tick.",
    },
    CurrentMinute: {
      category : "general",
      handler: `function () { return this.currentMinute; }`,
      highlight : false,
      deprecated : false,
      params: [],
      returnType: "number",
      isVariadicParameters: false,
      description : "The current minute.",
    },
    CurrentHour: {
      category : "general",
      handler: `function () { return this.currentHour; }`,
      highlight : false,
      deprecated : false,
      params: [],
      returnType: "number",
      isVariadicParameters: false,
      description : "The current hour.",
    },
    CurrentDay: {
      category : "general",
      handler: `function () { return this.currentDay; }`,
      highlight : false,
      deprecated : false,
      params: [],
      returnType: "number",
      isVariadicParameters: false,
      description : "The current day.",
    },
    CurrentWeek: {
      category : "general",
      handler: `function () { return this.currentWeek; }`,
      highlight : false,
      deprecated : false,
      params: [],
      returnType: "number",
      isVariadicParameters: false,
      description : "The current week.",
    },
    CurrentMonth: {
      category : "general",
      handler: `function () { return this.currentMonth; }`,
      highlight : false,
      deprecated : false,
      params: [],
      returnType: "number",
      isVariadicParameters: false,
      description : "The current month.",
    },
    CurrentYear: {
      category : "general",
      handler: `function () { return this.currentYear; }`,
      highlight : false,
      deprecated : false,
      params: [],
      returnType: "number",
      isVariadicParameters: false,
      description : "The current year.",
    },
    CurrentDayOfWeek: {
      category : "general",
      handler: `function () { return this.currentDayinWeek; }`,
      highlight : false,
      deprecated : false,
      params: [],
      returnType: "string",
      isVariadicParameters: false,
      description : "The current day of the week.",
    },
    CurrentDayName: {
      category : "general",
      foward: "DayFullName",
      highlight : false,
      deprecated : false,
      params: [],
      returnType: "string",
      isVariadicParameters: false,
      description : "The current day of the week. (full-name)",
    },
    CurrentDayShortName: {
      category : "general",
      foward: "DayShortName",
      highlight : false,
      deprecated : false,
      params: [],
      returnType: "string",
      isVariadicParameters: false,
      description : "The current day of the week. (short name)",
    },
    CurrentMonthName: {
      category : "general",
      forward: "MonthFullName",
      highlight : false,
      deprecated : false,
      params: [],
      returnType: "string",
      isVariadicParameters: false,
      description : "The current month. (full-name)",
    },
    CurrentMonthShortName: {
      category : "general",
      forward: "MonthShortName",
      highlight : false,
      deprecated : false,
      params: [],
      returnType: "string",
      isVariadicParameters: false,
      description : "The current month. (short name)",
    },
    CurrentTime24: {
      category : "general",
      forward: "Time24",
      highlight : false,
      deprecated : false,
      params: [],
      returnType: "string",
      isVariadicParameters: false,
      description : "The current time in 24 hour format.",
    },
    CurrentTime12: {
      category : "general",
      forward: "Time12",
      highlight : false,
      deprecated : false,
      params: [],
      returnType: "string",
      isVariadicParameters: false,
      description : "The current time in 12 hour format.",
    },
    CurrentDayPhase: {
      category : "general",
      handler: `function () { return this.currentDayPhase; }`,
      highlight : false,
      deprecated : false,
      params: [],
      returnType: "string",
      isVariadicParameters: false,
      description : "The current day phase.",
    },  




    /*
    SampleExpression: {
      // The category of the action as it appears in the expression picker
      category: "general",

      // Forward to the instance function name
      forward: "_SampleAction",
      // Or specify a handler function
      handler: `function () {
        // Your code here
      }`,

      // Set to true to automatically generate a script interface for this expression
      // Cases where you might not want this are:
      // 1- If you don't want it to appear in the script interface
      // 2- If the script interface has a better way to achieve the same thing
      autoScriptInterface: true,

      // Set to true to highlight the expression in the expression picker
      highlight: true,

      // Set to true to hide the expression in the interface. False by default if not specified.
      deprecated: false,

      // The type of the expression.
      returnType:
        - "string"
        - "number"
        - "any" // must be either string or number

      // Set to true if the expression is variadic. False by default if not specified.
      isVariadicParameters: false

      // list of parameters
      params: [
        {
          // The id of the parameter. This is used to generate the script interface.
          // It must be unique for each parameter.
          id: "param1",
          // The name of the parameter.
          name: "Param 1",
          // The description of the parameter.
          desc: "The first parameter",

          // The type of the parameter.
          type:
            // The following types can take a default value AND be automatically generated in the script interface
            - "string"
            - "number"
            - "any"
        },
      ],

      // The description of the expression as it appears in the expression picker
      description: "This is a sample expression",
    },
    */
  },
};
